spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wmsdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER